version: '3'

services:
  db:
    image: mysql:5.8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: djangoSample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes: # ホストPCとマウント
      # データ永続化のため、ローカルのmysqlフォルダと同期しておく
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  python:
    build: ./python
    command: uwsgi --socket :8001 --module app,uwsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose: # ???
      - "8001"
    depends_on: # ???
      - db

  nginx:
    image: nginx:1.13
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python
